### ISSUE TITLE
[BUG] RIT Team: set server with invalid URL

### ISSUE THREAD

**Issue by dmbarra** [ZupIT/ritchie-cli#91]
**What happened**:
Return a exception:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xbe1f55]

**What you expected to happen**:
Message show the URL is invalid

**How to reproduce it (as minimally and precisely as possible)**:
1 - rit set server
2 - https://localhost:8080

**Anything else we need to know?**:
 rit set server
URL of the server [http(s)://host] https://localhost:8080█
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xbe1f55]

goroutine 1 [running]:
github.com/ZupIT/ritchie-cli/pkg/server.SetterManager.Set(0xc000035800, 0x18, 0xc0000a6260, 0x16, 0x0, 0x0)
	/workspace/pkg/server/setter.go:35 +0xd5
github.com/ZupIT/ritchie-cli/pkg/cmd.setServerCmd.runFunc.func1(0xc0001f5600, 0x15790b0, 0x0, 0x0, 0x0, 0x0)
	/workspace/pkg/cmd/set_server.go:41 +0x93
github.com/spf13/cobra.(*Command).execute(0xc0001f5600, 0x15790b0, 0x0, 0x0, 0xc0001f5600, 0x15790b0)
	/home/circleci/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001a2580, 0x4420aa, 0x14f32c0, 0xc00005e778)
	/home/circleci/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/home/circleci/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/workspace/cmd/team/main.go:34 +0x2b

**Environment**:
- Ritchie version (use `rit --version`):
rit version 1.0.0-beta.6 (team)
  Build date: 05/06/20_18:00
  Built with: go1.14.2
- Operating System:
Linux/Ubuntu
- Network plugin / Tool and version (if this is a network-related / tool bug):
- Others:

**Comment by GuillaumeFalourd** [comment]
@dmbarra : do you still get this error since the last update ?
